# This is a basic workflow to help you get started with Actions

name: Screenshot

# Controls when the action will run.
on:
  schedule:
    - cron: '0 11 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: checkout
        uses: actions/checkout@v2

      - name: Install capture-website-cli
        shell: bash
        run: |
          echo "Installing capture-website-cli"
          npm install --global capture-website-cli 1> /dev/null
          echo "capture-website-cli installed successfully"

      - name: Screenshot Website
        shell: bash
        run: |
          capture-website "https://vacuumlabs.com" --output "./homepage-screenshot.jpeg" --full-page --scale-factor 1 --type jpeg
          capture-website "https://vacuumlabs.com/contact" --output "./contact-screenshot.jpeg" --full-page --scale-factor 1 --type jpeg
          echo "Screenshot done"

      - name: push
        run: |
          timestamp=$(date +'%Y-%m-%dT%H:%M:%S')
          mv homepage-screenshot.jpeg "./homepage/homepage-$timestamp.jpeg"
          mv contact-screenshot.jpeg "./contact/contact-$timestamp.jpeg"
          git config user.name MikiVlckova
          git config user.email miki.vlckova@vacuumlabs.com
          git add .
          git commit -m "generated"
          git push

