# This is a basic workflow to help you get started with Actions

name: Screenshot

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
    # branches: [ main ]
  # pull_request:
    # branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
  
#       - name: Create filename name
#         id: filename
#         run: echo "name=homepage-$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV  
      
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Install capture-website-cli
        shell: bash
        run: |
          echo "Installing capture-website-cli"
          npm install --global capture-website-cli 1> /dev/null
          echo "capture-website-cli installed successfully"

#       - name: Install imagemin
#         shell: bash
#         run: |
#           echo "Installing imagemin-cli"
#           npm install --global imagemin-cli
#           echo "imagemin-cli installed successfully"

      - name: Screenshot Website
        shell: bash
        run: |
          capture-website "https://vacuumlabs.com" --output "./homepage-screenshot.jpeg" --full-page --scale-factor 1 --type jpeg
          echo "Screenshot done"
      
      - name: push
        run: |
          ls > generated.txt
          mv homepage-screenshot.jpeg > "./homepage-$(date +'%Y-%m-%dT%H:%M:%S').jpeg"
          rm homepage-screenshot.jpeg
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
        
