# This is a basic workflow to help you get started with Actions

name: Screenshot

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
    # branches: [ main ]
  # pull_request:
    # branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
  
      - name: Get current date
        id: date
        run: echo "name=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV  
      
      - name: checkout
        uses: actions/checkout@v2
        
#       - name: Homepage Scfeenshot
#         uses: JonathanTreffler/full-website-screenshot-action@v1.0
#         with:
#           url: https://vacuumlabs.com
#           destination: ./homepage.png

      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://vacuumlabs.com
          destination: homepage-${{ steps.date.outputs.date }}.png
          full-page: true
          width: 1920 
      
      - name: push
        run: |
          ls > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
        
